FROM debian:stable-slim

RUN apt-get -q update && \
    apt-get -q -y install gnupg && \
    echo deb http://deb.liquidsoap.info/debian stable main >> /etc/apt/sources.list.d/liquidsoap.list && \
    curl -sL https://deb.nodesource.com/setup_11.x |  bash - && \
    apt-get -q -y install liquidsoap supervisor festival sox nodejs npm && \
    npm install -g typescript ts-node-dev && \
    apt-get clean

EXPOSE 9222   
EXPOSE 5000    

COPY ./scripts/ /scripts/
WORKDIR /scripts

RUN npm install && tsc


RUN touch /run.sh && chmod 777 /run.sh
COPY ./supervisor.sh /
COPY ./supervisord.conf /etc/

CMD ["liquidsoap", "-h"]