FROM debian:stable

MAINTAINER dee@labizbille.com

# Add package repo
RUN echo "deb http://deb.debian.org/debian stable main contrib non-free" > /etc/apt/sources.list

# Set up dependencies
RUN apt-get -y update && \
  apt-get -y install \
    dnsutils \
    telnet \
    build-essential \
    wget \
    curl \
    telnet \
    libmad0-dev \
    libshout3-dev \
    libvorbis-dev \
    libfdk-aac-dev \
    libid3tag0-dev \
    libmad0-dev \
    libshout3-dev \
    libasound2-dev \
    libpcre3-dev \
    libmp3lame-dev \
    libogg-dev \
    libtag1-dev \
    libssl-dev \
    libtool \
    libflac-dev \
    libogg-dev \
    libsamplerate-dev \
    libavutil-dev \
    libopus-dev \
    autotools-dev \
    autoconf \
    automake \
    ocaml-nox \
    opam \
    m4

# Set up filesystem and user
USER root
RUN useradd -m liquidsoap
RUN mkdir /var/log/liquidsoap
RUN chown -R liquidsoap:liquidsoap /var/log/liquidsoap
RUN chmod 766 /var/log/liquidsoap
RUN mkdir /etc/liquidsoap && chmod -R 755 /etc/liquidsoap

# Switch over so we can install OPAM
USER liquidsoap

# Initialize OPAM and install Liquidsoap and asssociated packages
RUN opam init -a
RUN opam update
RUN eval `opam config env`
RUN echo y | opam install ssl opus cry flac inotify lame mad ogg fdkaac samplerate taglib vorbis xmlplaylist liquidsoap


RUN apt-get -q -y install supervisor festival sox && \
    apt-get clean

RUN touch /run.sh && chmod 777 /run.sh
COPY ./supervisor.sh /
COPY ./supervisord.conf /etc/

CMD ["liquidsoap", "-h"]