FROM debian:stable-slim

RUN apt-get -q update && \
    apt-get -q -y install gnupg && \
    echo deb http://deb.liquidsoap.info/debian stable main >> /etc/apt/sources.list.d/liquidsoap.list && \
    apt-get -q -y install liquidsoap supervisor festival sox curl jq && \
    apt-get clean

RUN touch /run.sh && chmod 777 /run.sh
COPY ./supervisor.sh /
COPY ./supervisord.conf /etc/

CMD ["liquidsoap", "-h"]